global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'spring_boot_backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8081']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']