groups:
  - name: charging_station_alerts
    rules:
      # System metrics recording rules
      - record: system:cpu_usage
        expr: process_cpu_usage

      - record: system:memory_usage
        expr: jvm_memory_used_bytes{area="heap"}

      - record: http:request_rate
        expr: rate(http_server_requests_seconds_count[5m])

      - record: http:error_rate
        expr: rate(http_server_requests_seconds_count{status="5xx"}[5m])

      # Alert rules
      - alert: HighErrorRate
        expr: rate(reservations_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High reservation error rate
          description: "High reservation error rate detected"

      - alert: HighSystemLoad
        expr: process_cpu_usage > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High system load
          description: "High system load detected"

      - alert: HighMemoryUsage
        expr: jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"} > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: "Memory usage is above 90%"

      - alert: HighHttpErrorRate
        expr: rate(http_server_requests_seconds_count{status="5xx"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High HTTP error rate
          description: "HTTP 5xx error rate is above threshold"